### ISSUE TITLE
Some issue with "publish" target

### ISSUE THREAD

**Issue by awseward** [datNET/fs-fake-targets#28]
Not sure what the issue is, but it's something about a filepath it doesn't like.
Ran this in a pretty fresh/clean situation (post `git clean -xdf`)

Luckily, `packageandpublish` was still in there and seems to work for now.

Here's the output I got:

```
➜  fs-fake-targets git:(master) fake publish
Checking Paket version (downloading latest stable)...
Starting download from https://github.com/fsprojects/Paket/releases/download/2.63.1/paket.exe
Done.
Paket version 2.63.1.0
Skipping resolver for group Main since it is already up-to-date
C:\Users\Andrew\.babun\cygwin\home\Andrew\projects\datNET\fs-fake-targets\._fake\paket.lock is already up-to-date
4 seconds - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target Publish:
<== Publish

The resulting target order is:
 - Publish
Starting Target: Publish
Running build failed.
Error:
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at Fake.NuGetHelper.publish(NuGetParams parameters) in C:\code\fake\src\app\FakeLib\NuGet\NugetHelper.fs:line 289
   at Fake.NuGetHelper.NuGetPublish(FSharpFunc`2 setParams) in C:\code\fake\src\app\FakeLib\NuGet\NugetHelper.fs:line 377
   at datNET.Targets._PublishTarget@92.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
No target was successfully completed
---------------------------------------------------------------------
```

**Comment by mglodack** [comment]
Fixed by PR #34
