### ISSUE TITLE
Dependency on FAKE version

### ISSUE THREAD

**Issue by mglodack** [datNET/fs-fake-targets#82]
Looks like we might need to depend on a specific FAKE version.

Current project is on:
`4.14.2`

And this is the exception I am getting.

```
System.MissingMethodException: Method not found: 'Microsoft.FSharp.Core.FSharpOption`1<System.String> Fake.AssemblyInfoFile.GetAttributeValue(System.String, System.String)'.
   at datNET.Targets._readVersionString(String filePath)
   at datNET.Targets.VersionTargets.create@184-1.Invoke(String path)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at datNET.Targets.VersionTargets.create@182.Invoke(ConfigParams p)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483
```

I bumped my local `FAKE` version to `4.37.2` and that seemed to fix the issue.

**Comment by awseward** [comment]
Ah, yeah that function was probably introduced somewhere between `4.14.2` and `4.37.2`.

We'll definitely need a minimum version requirement then.

Might as well make it whatever the latest is now, yeah?

**Comment by mglodack** [comment]
@awseward That is a great idea
